#! /bin/sh


#bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-A-3 -d 1 2 3 4 5
bspc monitor HDMI-1-2 -d 1 2 3 4 5
bspc monitor DP-1-1 -d 1 2 3

bspc config border_width         1
bspc config window_gap          12
bspc config top_padding		30 # 40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#d8dee8"
bspc config normal_border_color  "#2f343f"
bspc config presel_feedback_color "#ff5c57"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a tor-browser state=floating
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

#sxhkd &

# Autostart scripts
for script in $HOME/.config/launch-scripts/*; do
	echo $script
	bash "$script" -H
done

feh --bg-center --bg-fill ~/Pictures/wallpapers/fsoc.jpg &
wmname LG3D & # Fix for Java based applications like Intellij
